#FILL ME IN ACCORDING TO THE FOLLOWING REQUIREMENTS
# 1) My base image should be compatible with node apps (for example, contain npm commands)
# 2) I want the code loaded into a directory called /app and set that dir as the home directory
# 3) ensure that all the required node modules are properly loaded (installed)
# 4) To run start this server, use the command `npm start`

# Also note that the app connects expects to connect to a redis database,
# it tries to connect to it using the REDIS_HOST env var
# Node apps run on port 3000 by default
