version: '3.1'
services:
  web:
    image: docker-workshop-node:latest
    environment:
     - REDIS_HOST=redis
    ports:
     - 3000:3000
    volumes:
     - ./node_app:/code
    depends_on:
     - redis
  redis:
    image: redis:latest
